spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vx-shop?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: lishuang001219


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect #指定默认mysql引擎为InnoDB
#  data:
#    rest:
#      base-path: /api