server:
  port: 8080

spring:
  datasource:
    username: root
    password: lishuang001219
    url: jdbc:mysql://localhost:3306/student-manager?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: cn.com.scitc.studentmanager.pojo

#showSql
logging:
  level:
    com:
      example:
        mapper : debug