server:
  port: 8080

spring:
  datasource:
    username: root
    password: lishuang001219
    url: jdbc:mysql://localhost:3306/webapp1901
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: cn.com.scitc.student.pojo

#showSql
logging:
  level:
    com:
      example:
        mapper : debug