server:
  port: 8989

spring:
  datasource:
    username: root
    password: lishuang001219
    url: jdbc:mysql://localhost:3306/webapp1901
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: cn.com.scitc.student.pojo

#showSql
logging:
  level:
    com:
      example:
        mapper : debug

jwt:
  header: Authorization
  tokenSecret: qazxswedcvfrtgbnhyujmkiolp #密钥
  tokenExpired: 3600000 #token过期时间(30分钟)